name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'  # Specify your .NET Core version

    - name: Build and Publish
      run: |
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet publish --configuration Release --output publish

    - name: Deploy to Server
      uses: appleboy/scp-action@master
      with:
        host: "130.225.170.52"
        username: "hwo"  # Replace with the SSH username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10300
        source: "publish/*"
        target: "/home/hwo/backend-pixel-crawler/"

    - name: Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: "130.225.170.52"
        username: "hwo"  # Replace with the SSH username
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10300
        script: |
          cd /home/hwo/backend-pixel-crawler
          # Add the command to restart your application, e.g.,
          sudo systemctl restart backend-pixel-crawler.dll
